### ISSUE TITLE
LoopDirection iota is not set

### ISSUE THREAD

**Issue by dkotik** [askeladdk/aseprite#2]
Dear friend,

Should that be an `iota` instead of `0`? I can submit a PR to fix it, just wanted to check with you incase it is an intentional stop gap. I will follow up on the other issue a little bit later.

```
const (
	Forward LoopDirection = 0
	Reverse
	PingPong
	PingPongReverse
)
```

**Comment by askeladdk** [comment]
Yes, you are correct. I actually noticed it yesterday and already committed a fix.
